let topicArray=[];
let topicNames=["Gems","Toys","Animals","Science_G7"];
topicArray.push(["img/diamond.png","Diamond","img/ruby.png","Ruby","img/emerald.png","Emerald","img/saphire.png","Saphire","img/opal.png","Opal","img/crystal.png","Crystal","img/garnet.png","Garnet","img/malachite.png","Malechite","img/lapis.png","Lapis-Lazuli","img/pyrites.png","Pyrites","img/topaz.png","Topaz","img/jasper.png","Jasper","img/beryl.png","Beryl","img/onyx.png","Onyx","img/chalcedony.png","Chalced-ony"]
)
topicArray.push(["img/play-toy/ball0sm.png","ball","img/play-toy/bearsm.png","bear","img/play-toy/bikesm.png","bike","img/play-toy/capsm.png","cap","img/play-toy/carsm.png","car","img/play-toy/dumptrucksm.png","dump truck","img/play-toy/fairysm.png","fairy","img/play-toy/firetrucksm.png","firetruck","img/play-toy/hatsm.png","hat","img/play-toy/lollipopsm.png","lollipop","img/play-toy/sockssm.png","socks","img/play-toy/shoesm.png","shoe","img/play-toy/shortssm.png","shorts","img/play-toy/tractorsm.png","tractor","img/play-toy/trucksm.png","truck","img/play-toy/tshirtsm.png","tshirt"]
)
topicArray.push(["img/animal/batsm.png","bat","img/animal/bunnysm.png","bunny","img/animal/catsm.png","cat","img/animal/clownfishsm.png","clownfish","img/animal/dogsm.png","dog","img/animal/dolphinsm.png","dolphin","img/animal/eaglesm.png","eagle","img/animal/emusm.png","emu","img/animal/fantailsm.png","fantail","img/animal/goldfishsm.png","goldfish","img/animal/horsesm.png","horse","img/animal/joeysm.png","joey","img/animal/kangaroosm.png","kangaroo","img/animal/kangaroosm.png","kangaroo","img/animal/kittensm.png","kitten","img/animal/owlsm.png","owl","img/animal/pelicansm.png","pelican","img/animal/penguinsm.png","penguin","img/animal/ponysm.png","pony","img/animal/puppysm.png","puppy","img/animal/rabbitsm.png","rabbit","img/animal/ratsm.png","rat","img/animal/seagullsm.png","seagull","img/animal/sealsm.png","seal","img/animal/whalesm.png","whale"]
)  
topicArray.push(["img/gensci/air.jpeg","air","img/gensci/bird.jpeg","bird","img/gensci/crustacean.jpeg","crustacean","img/gensci/crystal.jpeg","crystal","img/gensci/earth.jpeg","earth","img/gensci/electricity.jpeg","electricity","img/gensci/fire.jpeg","fire","img/gensci/fish.jpeg","fish","img/gensci/fossils.jpeg","fossils","img/gensci/geology.jpeg","geology","img/gensci/igneous.jpeg","igneous","img/gensci/insect.jpeg","insect","img/gensci/lizard.jpeg","lizard","img/gensci/mammal.jpeg","mammal","img/gensci/metamorphic.jpeg","meta-morphic","img/gensci/plant.jpeg","plant","img/gensci/sedimentary.jpeg","sedi-mentary","img/gensci/spark.jpeg","spark","img/gensci/water.jpeg","water"]
)